vocab: 2
iterations: 100
mini_batch_size: 1
batch_size: 1
temperature: 10
word_embedding_dim: 2
image_embedding_dim: 2
model_weights: vgg16.npy
learning_rate: 0.2
load_model: False
weight_decay: 0.0
display_rounds: False
display_comm_succ: True

log_path: logs

data_dir: data
image_dirs:
    - mice-10
    - dog-10
vocab:
    - miceword
    - catword
